on: push
name: Build Docker image
jobs:
  gitHubActionForMaven:
    name: GitHub Action for Maven
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: GitHub Action for Maven
      uses: LucaFeger/action-maven-cli@1.1.0
      with:
        args: clean package
    - name: Build Image
      run: |
        docker build -t difegue/doujinsoft -f ./Docker/Dockerfile .
    - name: Login to Docker Hub
      uses: actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Push Image
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: push difegue/doujinsoft
