on: push
name: Build Docker image
jobs:
  gitHubActionForMaven:
    name: GitHub Action for Maven
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: GitHub Action for Maven
      uses: LucaFeger/action-maven-cli@1.1.0
      with:
        args: clean package
    - name: Build and push Image
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin
        docker build -t difegue/doujinsoft -f ./Docker/Dockerfile .
        docker push difegue/doujinsoft
